package com.ui.character

sealed class MovementDirection
class UpDirection extends MovementDirection
class LeftDirection extends MovementDirection
class RightDirection extends MovementDirection
class DownDirection extends MovementDirection
